### ISSUE TITLE
The encoder-options attribute, when defined, is not applied to output result

### ISSUE THREAD

**Issue by nuxy** [sportheroes/aurelia-image-resizer#11]
**I'm submitting a bug report**

* **Framework Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 16.04 LTS)

* **Node Version:**
8.9.4

* **NPM Version:**
6.0.0

* **JSPM OR Webpack AND Version**
Aurelia CLI 0.33.0

* **Browser:**
Chrome Version 65.0.3325.181 (64-bit)
Firefox 59.0.2 (64-bit)

* **Language:**
all

**Current behavior:**

Using a modified example of the code provided [here](https://github.com/sportheroes/aurelia-image-resizer/blob/master/README.md#example-1) that includes `encoder-options`:
```
<file-reader
  file.bind="myFile"></file-reader>

<image-resizer
  if.bind="myFile"
  input.bind="myFile"
  output.bind="output"
  height="256"
  width="256"
  zoom.bind="zoom"
  encoder-options="0.5"></image-resizer>
```
The defined value is not applied to the `output` result.  The [`toDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) default value is used.

* **What is the expected behavior?**

The value when defined is applied to the `output` result.

**Comment by hadrienl** [comment]
Thank you, you can upgrade with npm ;)
