### ISSUE TITLE
keydown addEventListener() prevents right/left arrow keys to function in input fields

### ISSUE THREAD

**Issue by Falcosoft** [sportheroes/aurelia-image-resizer#13]
Hi,
First and foremost thank you for this very useful component. 
I would like to report a problem related to input fields on pages where also an image-resizer is placed.
The image-resizer component unconditionally adds event listeners to keydown events and also prevents default behavior (also the event listeners are not local to the component but installed at the document level). Because of this other form elements on the same page where an image-resizer is placed cannot process keyboard events such as left/right arrow keys (skip one character left/right).  
It would be very useful if there could be bindable properties defined whether the user of the component wants keyboard/mouse/touch event to be listened at all.
Thanks in advance.

**Comment by hadrienl** [comment]
Hello, thank you for your report, I see what is wrong [here](https://github.com/sportheroes/aurelia-image-resizer/blob/master/src/image-resizer/image-resizer.js#L156).

**Comment by Falcosoft** [comment]
Hi,
Thanks for your fast fix. Can you tell the foreseeable npm publishing date?

**Comment by hadrienl** [comment]
`'1.2.3': '2018-06-11T07:23:45.060Z'` ;)
