### ISSUE TITLE
TypeError: this.img is undefined in ImageResizerCustomElement

### ISSUE THREAD

**Issue by nuxy** [sportheroes/aurelia-image-resizer#6]
**I'm submitting a bug report**

* **Framework Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 14.0.4)

* **Node Version:**
7.10.0

* **NPM Version:**
4.0.5

* **JSPM OR Webpack AND Version**
Aurelia CLI 0.29.0

* **Browser:**
Chrome 58.0.3029.110 (64-bit)
Firefox 53.0.3 (64-bit)

* **Language:**
all

**Current behavior:**

Using a modified example of the code provided [here](https://github.com/sportheroes/aurelia-image-resizer/blob/master/README.md#example-1)
```
<file-reader
  file.bind="myFile"></file-reader>

<image-resizer
  if.bind="myFile"
  input.bind="myFile"
  output.bind="output"
  height="256"
  width="256"
  zoom.bind="zoom"></image-resizer>

<input
  type="number"
  value.bind="zoom">
```
I receive the following error in the latest versions of the Chrome and Firefox web browsers.
```
TypeError: this.img is undefined

Stacktrace:
_zoom            
zoomChanged      
selfSubscriber   
call             
bind             
bind             
_runValueChanged 
valueChanged 
selfSubscriber 
call 
setValue 
_configureDescriptor/descriptor.set 
setValue 
updateTarget 
call 
callSubscribers 
call 
flushMicroTaskQueue 
TaskQueue/this.requestFlushMicroTaskQueue<
```
The `zoomChanged` [event](https://github.com/sportheroes/aurelia-image-resizer/blob/master/src/image-resizer/image-resizer.js#L114) is being executed _before_  the `this.img` [object reference](https://github.com/sportheroes/aurelia-image-resizer/blob/master/src/image-resizer/image-resizer.html#L20) has been initialized.

**Expected behavior:**

No error occurs.

**Comment by hadrienl** [comment]
Thank you!
